name: Build and push docker images to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build, Push, and Test with My SQL
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      REPO_NAME: kuberepo
      BACKEND_IMAGE: asia-south1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/backendkube:latest
      FRONTEND_IMAGE: asia-south1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/frontendkube:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: authenticate gcp with remote
        run: gcloud config set project $PROJECT_ID

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Who am I?
        run: gcloud auth list

      - name: Build Backend Docker Image
        run: docker build -t $BACKEND_IMAGE .threetierkube/backend

      - name: Push Backend Image
        run: docker push $BACKEND_IMAGE

      - name: Build Frontend Docker Image
        run: docker build -t $FRONTEND_IMAGE .threetierkube/frontend

      - name: Push Frontend Image
        run: docker push $FRONTEND_IMAGE
        
      - name: Authenticate to GKE
        run: |
          # gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials privatecluster --region asia-south1 --project $PROJECT_ID

      # - name: verifying kubectl
      #   run: |
      #     kubectl version
      #     kubectl get nodes
        
      # - name: Deploy backend to GKE
      #   run: |
      #     kubectl apply -f backend/backend_deploy.yaml
      #     kubectl apply -f backend/backend_service.yaml

      # - name: Deploy frontend to GKE
      #   run: |
      #     kubectl apply -f frontend/frontend_deploy.yaml
      #     kubectl apply -f frontend/frontend_service.yaml
